### ISSUE TITLE
linter does not collour files well and throws errors...

### ISSUE THREAD

**Issue by rjboer** [AtomLinter/linter-golinter#95]
```
package main

import "fmt"
import "encoding/xml"

var data string = `
<table>
    <wfl>
        <wfw>23764</wfw>
        <wfl>Smith, Jane</wfl>
    </wfl>
    <wfl>
        <wfw>11111</wfw>
        <wfl>Doe, John</wfl>
    </wfl>
</table>
`

type Customer struct {
	Wfw string `xml:"wfw"`
	Wfl string `xml:"wfl"`
}

type Customers struct {
	Customers []Customer `xml:"wfl"`
}

func main() {
	var custs Customers

	err := xml.Unmarshal([]byte(data), &custs)

	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(custs)
}
```
linter latest version, code runs correct here:
https://play.golang.org/p/1xvGeuHGzJ
colours in atom under data var string=... line 6  dont look green, from line 19 onward it looks green (as in string like green)

if you put the ` on line 7 the text coloring works correct...

![capture](https://cloud.githubusercontent.com/assets/14197553/21949245/d84b7cd4-d9f0-11e6-9f10-7cde325db550.PNG)

**Comment by Arcanemagus** [comment]
The syntax highlighting would need to be fixed in whatever package is providing the Go language support in Atom, most likely [language-go](https://github.com/atom/language-go/issues).

If there is an issue with the lint results themselves first check whether `golint` on the CLI is returning the same results you are seeing inside Atom, if so (and they are wrong), you should file an issue on golint.

This project is merely a wrapper around `golint`, allowing it's results to be brought into Atom.

**Comment by rjboer** [comment]
ah...briljant remark....i'll do that!!
Thanks...!!
