### ISSUE TITLE
Error: spawn golint ENOENT

### ISSUE THREAD

**Issue by roryjf** [AtomLinter/linter-golinter#96]
The linter is functioning correctly in regards to its linting duties, but every time it runs, regardless of whether it finds any errors/warnings in the actual code, it gives me this error:

```
Error: spawn golint ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Anyone have any ideas on how to fix this?

**Comment by Arcanemagus** [comment]
That doesn't make any sense... if it's giving you that error then it can't find `golint` which you can solve by making sure `golint` is available on your `$PATH`, or by overriding the path in the settings.

Since you say you are getting results regardless of whether that error is showing, my only guess is that you have another provider that is also linting the Go code?

**Comment by Treebasher** [comment]
I was having this same issue after uninstalling the go-plus package and trying to use linter-golinter. Ultimately, I ended up uninstalling/reinstalling go, and uninstalling/reinstalling golint with go. After that, I restarted Atom and all was good again. If you don't know how to install golint, check https://github.com/golang/lint.

To add to @Arcanemagus's point, make sure your $GOPATH/bin is added to your system's $PATH. You shouldn't have to set it in this plugin's settings if you do this properly.

**Comment by jsejcksn** [comment]
I get this same error. I am just getting started with Go. Gettings started with `golint` in Atom on macOS is a mess for novices.

It appears that `golint` is not included with the macOS `.pkg` installer on the [downloads page](https://golang.org/dl/). Further, even if I manually install `golint` using `go get -u github.com/golang/lint/golint` (instructions provided by [the repo's readme](https://github.com/golang/lint)), I still get the error (presumably because the `go` installer does not create a `$GOPATH` or add `$HOME/go/bin` to my path, which is where `golint` gets installed). To add to the confusion, [this project's readme/settings page](https://atom.io/packages/linter-golinter) states:

> If the default path resolution of just `golint` is not working for you, you can use the command `which golint` on UNIX / OS X or `where.exe golint` on Windows in a terminal / command prompt to print the path to your `golint` installation. In most cases it should be `$GOPATH/bin/golint`.

which produces no output because `$HOME/go/bin` is not in my path, and therefore can't be searched for binaries using `which`.

Because I have *nix, experience I am aware of how to solve all of this, but for many beginners this has to be extremely confusing and frustrating.

**Comment by Arcanemagus** [comment]
@jsejcksn That readme is a bit out of date and comes from a time before many different attempts to fix the path on OS X had been introduced. It sounds like your issue is more with your Go setup not adding `$HOME/go/bin` to your `$PATH`, but I would be happy to review a PR updating the readme with better instructions!

**Comment by jsejcksn** [comment]
Hi @Arcanemagus. What I was saying is that this package does not work for macOS without manual intervention. macOS users must manually install `golint` and add the correct binary path to the package's settings page.

Is it possible to provide `golint` as a dependency of this package and reference the path of the provided `golint` binary when this package is added to Atom?

**Comment by Arcanemagus** [comment]
> Is it possible to provide golint as a dependency of this package?

@jsejcksn `golint` isn't a Node.js program, so no it can't be added as a dependency.

If you already have `golint` on your system and in your `$PATH`, then it should "just work". However macOS gives applications launched from the GUI a completely empty environment. Both Atom and the `exec()` library used here do several things to try to create a useable environment, but it's somewhat guesswork so it might not be working for you. You can blame Apple for that one 😛.

If you don't already have `golint` installed on your system, you need to do "manual intervention" regardless of what OS you are using.

**Comment by Arcanemagus** [comment]
I'm marking this as closed, the original filer hasn't responded in over a month and this is almost certainly a system setup issue.

**Comment by AlessioMartorelli** [comment]
Hope this could help you. As per @Arcanemagus comment this is purely a system configuration issue. I solved it making sure `golint` was installed and adding the $GOPATH/bin directory (where golint gets installed) to my $PATH:
In your bashrc:
```
export GOPATH=/path/to/your/go/dir
export PATH=$PATH:$GOPATH/bin
```

**Comment by jsejcksn** [comment]
I don't need help with it. I'm just advocating to make this more friendly to beginners who have little to no experience with the terminal or cli apps and want to get started with a linter in Atom. Just trying to reduce the number of steps required to make things work.

**Comment by Arcanemagus** [comment]
@jsejcksn I would imagine that a pre-requisite for writing Go code (and thus needing `linter-golinter` in the first place) would be a working Go setup.

**Comment by jsejcksn** [comment]
@Arcanemagus Absolutely. It's just that modifying one's `PATH` is not _necessary_ to a working `Go` setup.

I _still_ don't yet have a `GOPATH` environment variable or have my `Go` binaries directory in my `PATH` and I'm learning just fine. I don't think modifying my `PATH` every time I want to learn something new is a good idea. If I start seriously using `Go`, then I'll add it in.
